// ADDRESSES for hook.cpp
#define CODELEN 9
enum {
	C_D3DCREATE_CS,
	C_BEGINRENDERPLAYERS_CS, C_BEGINRENDERPLAYERS,
	C_BEGINRENDERPLAYERS2_CS, C_BEGINRENDERPLAYERS2,
	C_ENDRENDERPLAYERS_CS, C_ENDRENDERPLAYERS,
};

#define NOCODEADDR {0,0,0,0,0,0,0,0,0},
DWORD codeArray[][CODELEN] = { 
  // PES2008 DEMO
	{
		0x901ab1,
		0x9affd8, 0x88d1b0,
		0x8bfc6e, 0x88d1b0,
		0x88a852, 0x889f30,
	},
	// [Settings] PES2008 PC DEMO
  NOCODEADDR
};

#define DATALEN 1
enum {
	DUMMY,	
};

#define NODATAADDR {0},
DWORD dataArray[][DATALEN] = {
  // PES2008 DEMO
	NODATAADDR
	// [Settings] PES2008 PC DEMO
	NODATAADDR
};

DWORD code[CODELEN];
DWORD data[DATALEN];


